apiVersion: v1
kind: Service
metadata:
  name: real-time-data-pipeline-service
spec:
  selector:
    app: real-time-data-pipeline
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer